#ifndef PAYLOADPARSER_GLOBAL_H
#define PAYLOADPARSER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PAYLOADPARSER_LIBRARY)
#  define PAYLOADPARSERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PAYLOADPARSERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PAYLOADPARSER_GLOBAL_H
